host=''#From stalker db
user=''#From stalker db
password=''#From stalker db
token=''
chat_id=''
screens=''#Path to dir with screenshots. Example: /var/www/script/screen
send_file=''#Path to send.py
db_file=''#Path to todb.py
log_path=''#Path to 'log.txt'
todb_path=''#Path to todb.txt
